src: add log API
nodesource/nsolid pull request #135
Opened 2024-05-17 22:32 UTC by trevnorris

Add a C++ API to collect logs written with the nsolid JS API.

Log support for Winston and Pino will also be added.

2024-05-20 11:23 UTC, santigimeno requested changes

2024-05-20 11:23 UTC, santigimeno commented on src/nsolid.h
> + * @brief Regsiter a hook(function) to be called when a log line is written.
```suggestion
 * @brief Register a hook(function) to be called when a log line is written.
```

2024-05-20 11:23 UTC, santigimeno commented on src/nsolid/nsolid_api.h
> +  TSQueue<std::pair<SharedEnvInst, std::string>> on_log_write_q_;
We'll need to use a specific `struct` to store the associated metadata (log_level, etc.)

2024-05-20 11:23 UTC, santigimeno commented on src/nsolid.h
> +  (*static_cast<G*>(data))(inst, line);
Maybe use `std::move() here. I'm not too fond of those 2 string copies per hook call.
```suggestion
  (*static_cast<G*>(data))(inst, std::move(line));
```

2024-05-24 23:13 UTC, santigimeno approved these changes

2024-05-24 23:13 UTC, santigimeno commented on lib/nsolid.js
> +}
Should we check other types as well such as Buffer? I don't really know tbh

2024-05-24 23:13 UTC, santigimeno commented on src/nsolid.h
> +};
By looking at https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#log-and-event-record-definition, at the very least we should support:
- Timestamp
- TraceId / SpanId / TraceFlags if tracing is enabled.

We may add more later if we thing we need them.

2024-05-24 23:16 UTC, trevnorris commented on lib/nsolid.js
> +}
That's a good idea.

2024-05-24 23:25 UTC, santigimeno commented on src/nsolid.h
> +  (*static_cast<G*>(data))(inst, info);
I forgot to add... do you think it's possible to avoid making 2 copies of `LogWriteInfo` on every log?

2024-05-30 19:47 UTC, santigimeno approved these changes

2024-05-30 19:47 UTC, santigimeno commented on src/nsolid.h
> +}
Does the compiler know how to move LogWriteInfo or do we have to implement the move constructor ourselves?

2024-05-30 20:51 UTC, trevnorris commented on src/nsolid.h
> +}
`LogWriteInfo` contains only standard types that it knows how to move. So we should be fine.

2024-05-30 20:52 UTC, merged